#!/usr/bin/env node
// Stamp the TypeScript SDK version from the SINGLE source of truth: the repo-root
// VERSION file. Keeps package.json's `version` and the runtime `src/version.ts`
// (used for the `User-Agent`) in lockstep with the gateway spec + Python SDK, so
// the four version strings can never drift. Run automatically by `npm run
// generate:ts`; also safe to run standalone: `node scripts/sync-version.mjs`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, '..');
const versionFile = join(pkgDir, '..', '..', 'VERSION');

const version = readFileSync(versionFile, 'utf8').trim();
if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`sync-version: VERSION file has an unexpected value: "${version}"`);
  process.exit(1);
}

// package.json — update only the `version` field, preserve formatting otherwise.
const pkgPath = join(pkgDir, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
if (pkg.version !== version) {
  pkg.version = version;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
  console.log(`sync-version: package.json -> ${version}`);
}

// src/version.ts — runtime constant consumed by the hardening layer's User-Agent.
const versionTsPath = join(pkgDir, 'src', 'version.ts');
const versionTs = `// AUTO-GENERATED by scripts/sync-version.mjs from the repo-root VERSION file.
// Do NOT edit by hand — edit VERSION and run \`npm run generate:ts\`.
export const VERSION = '${version}';
`;
writeFileSync(versionTsPath, versionTs);
console.log(`sync-version: src/version.ts -> ${version}`);
